// Code generated by golex. DO NOT EDIT.

package parser

import (
	"bufio"
	"fmt"
	"log"
	"os"
)

var (
	src     = bufio.NewReader(os.Stdin)
	buf     []byte
	current byte
)

type yylexer struct {
	src     *bufio.Reader
	buf     []byte
	empty   bool
	current byte
}

func newLexer(src *bufio.Reader) (y *yylexer) {
	y = &yylexer{src: src}
	y.getc()
	return
}

func (y *yylexer) getc() byte {
	if y.current != 0 {
		y.buf = append(y.buf, y.current)
	}
	y.current = 0
	if b, err := y.src.ReadByte(); err == nil {
		y.current = b
	}
	if debug {
		fmt.Println("getc()->", string(y.current), y.current)
	}
	return y.current
}

func (y yylexer) Error(e string) {
	log.Fatal(e)
}

func (y *yylexer) Lex(lval *yySymType) int {
	// var err error
	c := y.current
	if y.empty {
		c, y.empty = y.getc(), false
	}

yystate0:

	y.buf = y.buf[:0]

	goto yystart1

yystate1:
	c = y.getc()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '!':
		goto yystate3
	case c == '"':
		goto yystate4
	case c == '&':
		goto yystate5
	case c == '+':
		goto yystate7
	case c == '-':
		goto yystate8
	case c == ':':
		goto yystate11
	case c == '\'':
		goto yystate6
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	case c == '^':
		goto yystate13
	case c == 'a':
		goto yystate14
	case c == 'c':
		goto yystate19
	case c == 'd':
		goto yystate31
	case c == 'e':
		goto yystate40
	case c == 'g':
		goto yystate50
	case c == 'l':
		goto yystate53
	case c == 'r':
		goto yystate61
	case c == 's':
		goto yystate65
	case c == 't':
		goto yystate66
	case c == 'u':
		goto yystate73
	case c == '|':
		goto yystate78
	case c >= '0' && c <= '9':
		goto yystate10
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'b' || c == 'f' || c >= 'h' && c <= 'k' || c >= 'm' && c <= 'q' || c >= 'v' && c <= 'z':
		goto yystate12
	}

yystate2:
	c = y.getc()
	switch {
	default:
		goto yyrule28
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = y.getc()
	goto yyrule8

yystate4:
	c = y.getc()
	goto yyrule2

yystate5:
	c = y.getc()
	goto yyrule6

yystate6:
	c = y.getc()
	goto yyrule1

yystate7:
	c = y.getc()
	goto yyrule4

yystate8:
	c = y.getc()
	switch {
	default:
		goto yyrule5
	case c == 'h':
		goto yystate9
	}

yystate9:
	c = y.getc()
	goto yyrule10

yystate10:
	c = y.getc()
	switch {
	default:
		goto yyrule26
	case c >= '0' && c <= '9':
		goto yystate10
	}

yystate11:
	c = y.getc()
	goto yyrule3

yystate12:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate13:
	c = y.getc()
	goto yyrule9

yystate14:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'd':
		goto yystate15
	case c == 'g':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c == 'e' || c == 'f' || c >= 'h' && c <= 'z':
		goto yystate12
	}

yystate15:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'd':
		goto yystate16
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate12
	}

yystate16:
	c = y.getc()
	switch {
	default:
		goto yyrule18
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate17:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate18
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate18:
	c = y.getc()
	switch {
	default:
		goto yyrule22
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate19:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'o':
		goto yystate20
	case c == 'r':
		goto yystate27
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c == 'p' || c == 'q' || c >= 's' && c <= 'z':
		goto yystate12
	}

yystate20:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'm':
		goto yystate21
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'l' || c >= 'n' && c <= 'z':
		goto yystate12
	}

yystate21:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'p':
		goto yystate22
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate12
	}

yystate22:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'l':
		goto yystate23
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate12
	}

yystate23:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate24
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate24:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 't':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate12
	}

yystate25:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate26
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate26:
	c = y.getc()
	switch {
	default:
		goto yyrule21
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate27:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate28:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'a':
		goto yystate29
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate12
	}

yystate29:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 't':
		goto yystate30
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate12
	}

yystate30:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate16
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate31:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate32
	case c == 'o':
		goto yystate37
	case c == 'u':
		goto yystate38
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'n' || c >= 'p' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate12
	}

yystate32:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'l':
		goto yystate33
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate12
	}

yystate33:
	c = y.getc()
	switch {
	default:
		goto yyrule19
	case c == 'e':
		goto yystate34
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate34:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 't':
		goto yystate35
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate12
	}

yystate35:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate36
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate36:
	c = y.getc()
	switch {
	default:
		goto yyrule19
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate37:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'n':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate12
	}

yystate38:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate39
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate39:
	c = y.getc()
	switch {
	default:
		goto yyrule23
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate40:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'd':
		goto yystate41
	case c == 'x':
		goto yystate44
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'w' || c == 'y' || c == 'z':
		goto yystate12
	}

yystate41:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'i':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate12
	}

yystate42:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 't':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate12
	}

yystate43:
	c = y.getc()
	switch {
	default:
		goto yyrule20
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate44:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'p':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate12
	}

yystate45:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'l':
		goto yystate46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate12
	}

yystate46:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'a':
		goto yystate47
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate12
	}

yystate47:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'i':
		goto yystate48
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate12
	}

yystate48:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'n':
		goto yystate49
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate12
	}

yystate49:
	c = y.getc()
	switch {
	default:
		goto yyrule13
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate50:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'u':
		goto yystate51
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate12
	}

yystate51:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'i':
		goto yystate52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate12
	}

yystate52:
	c = y.getc()
	switch {
	default:
		goto yyrule12
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate53:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'i':
		goto yystate54
	case c == 'o':
		goto yystate57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate54:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'k':
		goto yystate55
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z':
		goto yystate12
	}

yystate55:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate56:
	c = y.getc()
	switch {
	default:
		goto yyrule24
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate57:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'g':
		goto yystate58
	case c == 'o':
		goto yystate59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate58:
	c = y.getc()
	switch {
	default:
		goto yyrule14
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate59:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'p':
		goto yystate60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate12
	}

yystate60:
	c = y.getc()
	switch {
	default:
		goto yyrule25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate61:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate62:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'm':
		goto yystate63
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'l' || c >= 'n' && c <= 'z':
		goto yystate12
	}

yystate63:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'o':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate64:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'v':
		goto yystate35
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'u' || c >= 'w' && c <= 'z':
		goto yystate12
	}

yystate65:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'e':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate12
	}

yystate66:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'a':
		goto yystate67
	case c == 'o':
		goto yystate71
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate67:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'g':
		goto yystate68
	case c == 's':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate12
	}

yystate68:
	c = y.getc()
	switch {
	default:
		goto yyrule17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate69:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'k':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z':
		goto yystate12
	}

yystate70:
	c = y.getc()
	switch {
	default:
		goto yyrule16
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate71:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'd':
		goto yystate72
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate12
	}

yystate72:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'o':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate73:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'i':
		goto yystate74
	case c == 'n':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate12
	}

yystate74:
	c = y.getc()
	switch {
	default:
		goto yyrule11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate75:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'd':
		goto yystate76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate12
	}

yystate76:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == 'o':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate12
	}

yystate77:
	c = y.getc()
	switch {
	default:
		goto yyrule15
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate12
	}

yystate78:
	c = y.getc()
	goto yyrule7

yyrule1: // "'"
	{

		lval.str = string(y.buf)
		return QUOTE
	}
yyrule2: // "\""
	{

		lval.str = string(y.buf)
		return DQUOTE
	}
yyrule3: // ":"
	{

		lval.str = string(y.buf)
		return COLON
	}
yyrule4: // "+"
	{

		lval.str = string(y.buf)
		return PLUS
	}
yyrule5: // "-"
	{

		lval.str = string(y.buf)
		return MINUS
	}
yyrule6: // "&"
	{

		lval.str = string(y.buf)
		return AND
	}
yyrule7: // "|"
	{

		lval.str = string(y.buf)
		return OR
	}
yyrule8: // "!"
	{

		lval.str = string(y.buf)
		return NOT
	}
yyrule9: // "^"
	{

		lval.str = string(y.buf)
		return XOR
	}
yyrule10: // "-h"
	{

		lval.str = string(y.buf)
		return HELP
	}
yyrule11: // "ui"
	{

		lval.str = string(y.buf)
		return UI
	}
yyrule12: // "gui"
	{

		lval.str = string(y.buf)
		return GUI
	}
yyrule13: // "explain"
	{

		lval.str = string(y.buf)
		return EXPLAIN
	}
yyrule14: // "log"
	{

		lval.str = string(y.buf)
		return LOG
	}
yyrule15: // "undo"
	{

		lval.str = string(y.buf)
		return UNDO
	}
yyrule16: // "todo"|"task"
	{

		lval.str = string(y.buf)
		return TASK
	}
yyrule17: // "tag"
	{

		lval.str = string(y.buf)
		return TAG
	}
yyrule18: // "add"|"create"
	{

		lval.str = string(y.buf)
		return ADD
	}
yyrule19: // "del"|"delete"|"remove"
	{

		lval.str = string(y.buf)
		return DELETE
	}
yyrule20: // "set"|"edit"
	{

		lval.str = string(y.buf)
		return SET
	}
yyrule21: // "done"|"complete"
	{

		lval.str = string(y.buf)
		return DONE
	}
yyrule22: // "age"
	{

		lval.str = string(y.buf)
		return AGE
	}
yyrule23: // "due"
	{

		lval.str = string(y.buf)
		return DUE
	}
yyrule24: // "like"
	{

		lval.str = string(y.buf)
		return LIKE
	}
yyrule25: // "loop"
	{

		lval.str = string(y.buf)
		return LOOP
	}
yyrule26: // {digit}
	{

		lval.str = string(y.buf)
		return NUM
	}
yyrule27: // {identifier}
	{

		lval.str = string(y.buf)
		return IDENT
	}
yyrule28: // {white}
	if true { // avoid go vet determining the below panic will not be reached
		{
		}
		goto yystate0
	}
	panic("unreachable")

yyabort: // no lexem recognized
	//
	// silence unused label errors for build and satisfy go vet reachability analysis
	//
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
	}

	y.empty = true
	return int(c)
}
